name: Update README with a joke

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get a random joke
      id: joke
      run: |
        joke=$(curl -s https://v2.jokeapi.dev/joke/Any?type=single | jq -r '.joke')
        echo "$joke" > joke.txt

    - name: Update README.md
      run: |
        joke=$(cat joke.txt)
        sed -i "s/<!-- joke-placeholder -->.*/<!-- joke-placeholder -->\n$joke/" README.md

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add README.md
        git commit -m "Add daily joke"
        git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main