name: Update Python Joke

on:
  schedule:
    - cron: '0 12 * * *' 
  push:
    branches:
      - main

jobs:
  update-joke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Fetch joke and update README
      run: |
        joke=$(curl -H "Accept: text/plain" https://icanhazdadjoke.com/)
        echo "Joke: $joke"
        sed -i 's|<!-- joke-placeholder -->|'"$joke"'|g' README.md

    - name: Commit the updated README
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update joke in README"
        git push https://$GH_TOKEN@github.com/Davsooonowy/Davsooonowy.git
